### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by KayTsujita** [KayTsujita/protospace-39062#1]
#URL
https://protospace-39062.onrender.com

**Comment by shodai-ito** [comment]
@KayTsujita さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
アプリの仕様上、トップページに表示されるユーザー名には敬称も表示されるようにしましょう！

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by KayTsujita** [comment]
ご確認ありがとうございます。
ご指摘箇所修正し、フォームからの提出完了しました。
どうぞよろしくお願いいたします。

**Comment by shodai-ito** [comment]
@KayTsujita さん、再度ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by KayTsujita** [comment]
早速のご確認ありがとうございます！
LGTMいただきありがとうございます。

最終課題も引き続きどうぞよろしくお願いいたします！

**Comment by KayTsujita** [comment]
ありがとうございました。
